name: TSA
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - pytorch-cuda
  - torchvision=0.15.2
  - torchaudio=2.1.0
  - cudatoolkit=11.8
  - numpy=1.26.2
  - transformers=4.36.0
  - pyyaml=6.0.1
  - pip
  - pip:
      - doc-ufcn==0.2.0rc4
      - huggingface-hub==0.20.2