# config.yaml

models:
  transcription:
    path: "models/transcription_full"  
    batch_size: 40
    precision: "half"
    num_beams: 1
  
  # These remain unchanged
  line_extraction: "models/textlines_full/model.pth"
  row_extraction: "models/rows_full/model.pth"
  column_extraction: "models/columns_full/model.pth"

directories:
  # Base directories for input/output
  input: "examples/inputs"
  output: "examples/outputs"
  temp: "examples/tmp" 
  
  # Configuration files
  page_classification: "layout_classification/page_classifications.csv"
  table_guide: "layout_classification/table_layouts.csv"