# config.yaml

models:
  # Path to transcription model directory (used for processor, tokenizer, and model)
  transcription: "models/transcription_nievre"
  
  # Paths to various model weights
  line_extraction: "models/textlines_nievre/model.pth"
  row_extraction: "models/rows_nievre/model.pth"
  column_extraction: "models/columns_nievre/model.pth"

directories:
  # Base directories for input/output
  input: "/media/aurelius/Seagate Expansion Drive/Work/TSA/Nievre/"
  output: "/media/aurelius/Seagate Expansion Drive/Work/TSA/Results_V2/"
  
  # Configuration files
  page_classification: "layout_classification/page_classifications_nievre.csv"
  table_guide: "layout_classification/table_layouts.csv"