#!/usr/bin/env python3
"""Write a per-departement inference config derived from the production base config.

The base config (configs/recommended_grid_v2.yaml) carries the validated model
paths, grid/line-split settings and normalisation stats. This script copies it
verbatim and overrides ONLY the three directory fields that change per
departement: directories.input, directories.output and directories.temp.

Model paths and the page_classification / table_guide CSV paths are left exactly
as they appear in the base config. In the production config these are
repo-relative (for example "models/rows_v7/model.pth"); inference.py resolves
them against the current working directory, so inference MUST be run from the
repo root. The HPC worker (run_department.sh) always does this.

Usage:
    python scripts/hpc/make_config.py \
        --department Paris \
        --input-dir  /scratch/tsa/Paris/images \
        --output-dir /scratch/tsa/Paris/output \
        --out        configs/generated/Paris.yaml

If --temp-dir is omitted it defaults to <output-dir>/tmp.
If --out is omitted it defaults to configs/generated/<department>.yaml
(relative to the repo root).
"""

import argparse
import sys
from pathlib import Path

import yaml

# Repo root = two levels up from this file (scripts/hpc/make_config.py).
REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_BASE = REPO_ROOT / "configs" / "recommended_grid_v2.yaml"


def build_config(base_config: Path, input_dir: Path, output_dir: Path,
                 temp_dir: Path) -> dict:
    """Load the base config and override only the three directory fields."""
    with base_config.open("r") as fh:
        cfg = yaml.safe_load(fh)

    if not isinstance(cfg, dict):
        raise ValueError(f"Base config did not parse to a mapping: {base_config}")
    if "directories" not in cfg or not isinstance(cfg["directories"], dict):
        raise ValueError(f"Base config has no 'directories' section: {base_config}")

    # Store directories as absolute paths so they are unambiguous regardless of
    # the working directory. Model / layout paths are intentionally left as-is
    # (repo-relative in the production config).
    cfg["directories"]["input"] = str(input_dir)
    cfg["directories"]["output"] = str(output_dir)
    cfg["directories"]["temp"] = str(temp_dir)
    return cfg


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--department", required=True,
                        help="Departement name (used for default --out and a header comment)")
    parser.add_argument("--input-dir", required=True,
                        help="Directory containing the extracted page images for this departement")
    parser.add_argument("--output-dir", required=True,
                        help="Directory where the pipeline writes its CSV tables (under output/pages/...)")
    parser.add_argument("--temp-dir", default=None,
                        help="Temp directory (default: <output-dir>/tmp)")
    parser.add_argument("--base-config", default=str(DEFAULT_BASE),
                        help=f"Base config to derive from (default: {DEFAULT_BASE})")
    parser.add_argument("--out", default=None,
                        help="Where to write the generated YAML "
                             "(default: configs/generated/<department>.yaml)")
    args = parser.parse_args()

    base_config = Path(args.base_config).expanduser().resolve()
    if not base_config.is_file():
        print(f"ERROR: base config not found: {base_config}", file=sys.stderr)
        return 1

    input_dir = Path(args.input_dir).expanduser().resolve()
    output_dir = Path(args.output_dir).expanduser().resolve()
    temp_dir = (Path(args.temp_dir).expanduser().resolve()
                if args.temp_dir else output_dir / "tmp")

    if args.out:
        out_path = Path(args.out).expanduser().resolve()
    else:
        out_path = REPO_ROOT / "configs" / "generated" / f"{args.department}.yaml"

    cfg = build_config(base_config, input_dir, output_dir, temp_dir)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    header = (f"# Auto-generated by scripts/hpc/make_config.py for departement: "
              f"{args.department}\n"
              f"# Derived from: {base_config.name} (only directories.* overridden)\n")
    with out_path.open("w") as fh:
        fh.write(header)
        yaml.safe_dump(cfg, fh, default_flow_style=False, sort_keys=False,
                       allow_unicode=True)

    print(str(out_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
